#!/usr/bin/env php
<?php

$config = require_once(__DIR__ . '/app/config.php');

/*
 * PHP version requirement
 */
if( version_compare( PHP_VERSION, $config['php-min'], '>=' ) == false )
{
	echo "pug: Requires PHP {$config['php-min']}+, found " . PHP_VERSION . PHP_EOL;
	exit( 1 );
}

/*
 * Autoload
 */
$autoload = require_once(__DIR__ . '/app/autoload.php');

foreach($autoload as $module => $path)
{
	$file = __DIR__ . "/{$path}/Autoloader.php";

	if(file_exists($file))
	{
		include_once($file);
		call_user_func("{$module}\Autoloader::register");
	}
	else
	{
		$install = strtolower (readline ("{$config['name']}: Install missing dependencies [yes]? "));

		switch ($install)
		{
			case '':
			case 'y':
			case 'yes':
				chdir (__DIR__);
				exec ('git submodule update --init');
				exit (0);
				break;

			default:
				exit (1);
				break;
		}
	}
}

/*
 * App configuration
 */
$app = new Huxtable\Application($config['name'], $config['version']);

/*
 * Register commands
 */
require_once(__DIR__ . '/app/commands.php');

if(isset($commands) && is_array($commands))
{
	foreach($commands as $command)
	{
		if($command instanceof Huxtable\Command)
		{
			$app->registerCommand($command);
		}
		else
		{
			echo "Invalid command registered in 'app/commands.php'".PHP_EOL;
			exit(1);
		}
	}
}

$app->unregisterCommand('version');

/*
 * User config
 */
$userConfigPath = __DIR__ . '/config.php';

if( !file_exists($userConfigPath) )
{
	copy( $userConfigPath . '.dist', $userConfigPath );
}

$userConfig = require_once( $userConfigPath );

/*
 * Timezone
 */
$timezone = 'UTC';

// Override with value from php.ini if set
if( strlen( $iniTimezone = ini_get( 'date.timezone' ) ) > 0 )
{
	$timezone = $iniTimezone;
}

// Override with value from config.php if set
if( isset( $userConfig['timezone'] ) )
{
	$timezone = $userConfig['timezone'];
}

date_default_timezone_set( $timezone );

// Attempt to run the requested command
$app->run();

// Stop application and exit
$app->stop();

?>
